title: John Sous
description: Essays on physics, research, and scientific practice.
lang: en
baseurl: ""
url: "https://jsous.github.io"
permalink: pretty

exclude:
  - .bundle
  - .jekyll-cache
  - .sass-cache
  - README.md
  - Gemfile
  - Gemfile.lock
  - drafts
  - vendor
