title: John Sous
description: Minimal starter website for the John Sous research lab at Yale University.
affiliation: Yale University
lang: en
baseurl: ""
url: ""
permalink: pretty
goatcounter_site: ""
